version: "2.1"
services:

  dns:
    image: mvance/unbound:latest
    networks:
      net:
        ipv4_address: 192.168.19.2
        ipv6_address: fd19:19:19::2
    restart: always
    
  vpn:
    image: cmulk/wireguard-docker:buster
    volumes:
     - ./data/wg/:/etc/wireguard/:rw
    networks:
      net:
        ipv4_address: 192.168.19.3
        ipv6_address: fd19:19:19::3
    ports:
     - 1194:1194/udp
    restart: always
    cap_add:
     - NET_ADMIN
     - SYS_MODULE

  
  ipv6nat-mailcow:
    environment:
      - TZ="America/Los Angeles"
    image: robbertkl/ipv6nat
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.19.0/24
        - subnet: fd19:19:19::0/64
